import { test } from 'node:test';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { detectRepo, generateAgentsMd } from '../dist/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixture = join(here, 'fixtures', 'node-ts');

test('detectRepo identifies a TypeScript/Node project', () => {
  const facts = detectRepo(fixture);

  assert.equal(facts.name, 'sample-widget');
  assert.equal(facts.description, 'A sample widget library used as a test fixture.');
  assert.equal(facts.license, 'MIT');
  assert.equal(facts.packageManager, 'pnpm', 'pnpm-lock.yaml should select pnpm');
  assert.equal(facts.nodeVersion, '>=18');
  assert.ok(facts.languages.includes('TypeScript'), 'tsconfig should signal TypeScript');
  assert.ok(facts.languages.includes('JavaScript'));
  assert.ok(facts.frameworks.includes('Express'), 'express dep should be detected');
  assert.ok(facts.frameworks.includes('Vitest'));
  assert.equal(facts.isEmpty, false);
});

test('detectRepo extracts commands from package.json scripts', () => {
  const facts = detectRepo(fixture);
  const byLabel = Object.fromEntries(facts.commands.map((c) => [c.label, c.command]));

  assert.equal(byLabel.Install, 'pnpm install');
  assert.equal(byLabel.Build, 'pnpm build');
  assert.equal(byLabel.Test, 'pnpm test');
  assert.equal(byLabel.Lint, 'pnpm lint');
  assert.equal(byLabel.Develop, 'pnpm dev');
});

test('detectRepo lists known directories', () => {
  const facts = detectRepo(fixture);
  const paths = facts.directories.map((d) => d.path);

  assert.ok(paths.includes('src/'));
  assert.ok(paths.includes('test/'));
  assert.ok(paths.includes('docs/'));
});

test('generateAgentsMd renders the expected sections', () => {
  const facts = detectRepo(fixture);
  const md = generateAgentsMd(facts);

  assert.match(md, /^# AGENTS\.md — sample-widget/m);
  assert.match(md, /## Project overview/);
  assert.match(md, /## Setup/);
  assert.match(md, /## Build & run/);
  assert.match(md, /## Test/);
  assert.match(md, /## Lint & format/);
  assert.match(md, /## Project structure/);
  assert.match(md, /## Conventions & notes for agents/);
  assert.match(md, /## Do \/ Don/);

  // Real, detected facts must appear.
  assert.match(md, /pnpm install/);
  assert.match(md, /pnpm test/);
  assert.match(md, /\*\*Language:\*\* TypeScript, JavaScript/);
  assert.match(md, /generated by \[mkagents\]/i);
});

test('generateAgentsMd never includes empty command sections', () => {
  // A bare project with only a name should omit Build/Test/Lint sections.
  const facts = {
    root: '/tmp/x',
    name: 'bare',
    languages: [],
    frameworks: [],
    commands: [],
    workspaces: [],
    directories: [],
    isGitRepo: false,
    isEmpty: false,
  };
  const md = generateAgentsMd(facts);

  assert.doesNotMatch(md, /## Build & run/);
  assert.doesNotMatch(md, /## Test/);
  assert.doesNotMatch(md, /## Lint & format/);
  // Overview + conventions + do/don't are always safe to include.
  assert.match(md, /## Project overview/);
  assert.match(md, /## Conventions & notes for agents/);
});
